Fixes an error with Unity 2017.3.1
error CS0234: The type or namespace name `WSA' does not exist in the namespace `UnityEngine.VR'. Are you missing an assembly reference?

Since this namespace is unsused, I deleted the using directive.